Updated ruby version to 3.3 in Dockerfile to resolve rubygems issue:
ERROR:  Error installing rubygems-update:
rubygems-update-3.6.3 requires Ruby version >= 3.1.0. The current ruby version is 3.0.7.220.